name: white-orchid-risk-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - scikit-learn==1.5.2
      - pandas==2.1.4
      - numpy==1.26.2
      - joblib==1.3.2
      - inference-schema
      - azureml-inference-server-http
      - opencensus-ext-azure==1.1.13
